/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c15e5559-5fd5-4424-84d6-46c49f142d01",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o9VCemzGy",
    "aws_user_pools_web_client_id": "7b4mc9pnromjeprvqj9qt3luik",
    "oauth": {}
};


export default awsmobile;
